name: CIasdasdja

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      - name: enable ssh
        run: sudo - i
      - run: sudo apt update
