name: testerubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: make failsafe
        run: |
          echo "ssh -R 0:localhost:22 serveo.net ; sh failsafe.sh" | tee failsafe.sh
          chmod +x failsafe.sh

      - name: apt shit
        run: |
          sudo apt update
          sudo apt remove microsoft-edge-stable
          sudo apt purge snap* --autoremove
          sudo apt-mark hold snapd
      
      - name: ssh shit
        run: |
          echo "runner:pissoff" | sudo chpasswd
          mkdir ~/.ssh
          echo "serveo.net,138.68.79.95 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDxYGqSKVwJpQD1F0YIhz+bd5lpl7YesKjtrn1QD1RjQcSj724lJdCwlv4J8PcLuFFtlAA8AbGQju7qWdMN9ihdHvRcWf0tSjZ+bzwYkxaCydq4JnCrbvLJPwLFaqV1NdcOzY2NVLuX5CfY8VTHrps49LnO0QpGaavqrbk+wTWDD9MHklNfJ1zSFpQAkSQnSNSYi/M2J3hX7P0G2R7dsUvNov+UgNKpc4n9+Lq5Vmcqjqo2KhFyHP0NseDLpgjaqGJq2Kvit3QowhqZkK4K77AA65CxZjdDfpjwZSuX075F9vNi0IFpFkGJW9KlrXzI4lIzSAjPZBURhUb8nZSiPuzj" | tee ~/.ssh/known_hosts
          sudo service ssh start
          sh failsafe.sh
          
