name: testerubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: make failsafe
        run: |
          echo "ssh -R 0:localhost:22 serveo.net ; sh failsafe.sh" | tee failsafe.sh
          chmod +x failsafe.sh

      - name: apt shit
        run: |
          sudo apt update
          sudo apt remove microsoft-edge-stable
          sudo apt purge snap* --autoremove
          sudo apt-mark hold snapd
      
      - name: ssh shit
        run: |
          echo "runner:pissoff" | sudo chpasswd
          mkdir ~/.ssh
          echo "serveo.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDxYGqSKVwJpQD1F0YIhz" | tee ~/.ssh/known_hosts
          sudo service ssh start
          sh failsafe.sh
          
