name: Ubuntu (GitHub Edition)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #  - uses: actions/checkout@v4

      - name: Make Failsafe Script
        run: |
          cd /
          sudo mkdir scriptinit
          sudo chown runner /scriptinit
          cd scriptinit
          echo "sudo service ssh restart ; ssh -R 0:localhost:22 serveo.net ; sh failsafe.sh" | tee failsafe.sh
          chmod +x failsafe.sh

      - name: Configure System And Install KDE and VNC
        run: |
          cd /scriptinit
          sudo apt update
          sudo apt install tigervnc-standalone-server kde-plasma-desktop dbus-x11 -y
          sudo systemctl enable --now sddm
          sudo apt remove microsoft-edge-stable
          sudo apt purge snap* --autoremove
          sudo apt-mark hold snapd
          git clone https://github.com/novnc/novnc/
          echo "vncserver -SecurityTypes none -rfbport 5901 ; ./novnc/utils/novnc_proxy --listen localhost:6969 --vnc localhost:5901" | tee startvnc.sh
          chmod +x startvnc.sh
          
      - name: SSH Server Init and Login
        run: |
          cd /scriptinit
          echo "runner:192820" | sudo chpasswd
          mkdir ~/.ssh
          echo "serveo.net,138.68.79.95 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDxYGqSKVwJpQD1F0YIhz+bd5lpl7YesKjtrn1QD1RjQcSj724lJdCwlv4J8PcLuFFtlAA8AbGQju7qWdMN9ihdHvRcWf0tSjZ+bzwYkxaCydq4JnCrbvLJPwLFaqV1NdcOzY2NVLuX5CfY8VTHrps49LnO0QpGaavqrbk+wTWDD9MHklNfJ1zSFpQAkSQnSNSYi/M2J3hX7P0G2R7dsUvNov+UgNKpc4n9+Lq5Vmcqjqo2KhFyHP0NseDLpgjaqGJq2Kvit3QowhqZkK4K77AA65CxZjdDfpjwZSuX075F9vNi0IFpFkGJW9KlrXzI4lIzSAjPZBURhUb8nZSiPuzj" | tee ~/.ssh/known_hosts
          sh failsafe.sh
          
